### ISSUE TITLE
Option to skip file integrity

### ISSUE THREAD

**Issue by null15** [austinh115/BSWLauncher#1]
Is there any way you can make the launcher skip the file integration part, and go straight to login?

**Comment by lazarus** [comment]
It does, only checks integrity if local version cache doesnt match remote

If you want to hardcode it to not verify files, change https://github.com/austinh115/BSWLauncher/blob/master/main.go#L38 from LOCAL to CDN

**Comment by null15** [comment]
How do you compile your source to exe? Could you change LOCAL to CDN and compile it to an exe for me?

After compiling (go build main.go) I get this: 
![image](https://user-images.githubusercontent.com/30800470/108621237-d1fa6680-7431-11eb-8ce3-461d0856581e.png)

**Comment by lazarus** [comment]
Clone to GOPATH project location

```bat
set GOROOT=C:\Go #gosetup

set GOPATH=C:\Users\Austin\go #gosetup

C:\Go\bin\go.exe build -o "C:\Program Files (x86)\Burning SoulWorker\launcher.exe" BSWLauncher #gosetup

C:\Users\Austin\go\src\BSWLauncher\res\rsrc.exe -manifest launcher.exe.manifest -o ../launcher.syso -arch 386 -ico launcher.ico
```

**Comment by null15** [comment]
I made a folder called BSWLauncher in src folder, then cloned this github there, opened cmd and ran 

C:\Go\bin\go.exe build -o "C:\Program Files (x86)\Burning SoulWorker\launcher.exe" BSWLauncher #gosetup

But got this: 

![image](https://user-images.githubusercontent.com/30800470/108628856-50b8c900-745d-11eb-85e4-c53242f4311b.png)

**Comment by null15** [comment]
And sometimes 
![image](https://user-images.githubusercontent.com/30800470/108629148-e2750600-745e-11eb-89b6-ea5a4a786dd2.png)

**Comment by null15** [comment]
I made sure the root root dir and path dir is all correct, maybe it has something to do with #gosetup?

**Comment by lazarus** [comment]
Run `go get ./...` to  make sure you've installed all the dependencies

Use GoLand and open the project there if it's not working

I'm not really interested in providing golang help, you can remove #gosetup, don't think it does anything--just a label
If any errors persist, look for solutions in the proper place
