### ISSUE TITLE
Error with launcher

### ISSUE THREAD

**Issue by null15** [austinh115/BSWLauncher#3]
![image](https://user-images.githubusercontent.com/30800470/108623995-505f0480-7442-11eb-956b-46680fe0e0fb.png)

I believe its a problem with the launcher, my account is many years old and I play it on a daily basis, happens me and my friend

**Comment by lazarus** [comment]
Keep BSW open

Download [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)

Run it as admin

Find BurningSW.exe and open it, send the command line field value here, e.g.
`BurningSW.exe HID:Username TOKEN:3f5776e7-325a-4c00-ad00-9900aa002d18 CHCODE:11 IP:51.210.216.79 PORT:10000`

**Comment by null15** [comment]
Ok, on it

**Comment by null15** [comment]
Is there a way for me to send this in private? Or is it fine?

**Comment by lazarus** [comment]
Austin#0008, fine to send it here as well, it changes every time you login

**Comment by null15** [comment]
BurningSW.exe HID:Username TOKEN:d2581ad5-74d2-4385-bdcf-940b7199f09f CHCODE:11 IP:51.210.216.79 PORT:10000

**Comment by null15** [comment]
I changed HID, or should I not? In the reply above

**Comment by lazarus** [comment]
It's fine. 

Does it work with official launcher, or same error?

**Comment by null15** [comment]
Official launcher works, can play just fine there

**Comment by lazarus** [comment]
Then use that?

If you're saving login data, try deleting launcher_config.json and try again

**Comment by null15** [comment]
I would like to use yours, and then have it force not to verify files, it would be a charm (LOCAL to CDN), but I fail to compile it so I cannot make this change, it would be really amazing if you could do it for me austin (the compiling part)

**Comment by lazarus** [comment]
[launcher.zip](https://github.com/austinh115/BSWLauncher/files/6017949/launcher.zip)

**Comment by lazarus** [comment]
Disabled patching completely
